sudo: false
language: node_js
node_js:
- '4'
- '5'
- '6'
cache:
  directories:
  - node_modules
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
install:
- export CXX="g++-4.8"
- npm install
- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile
  --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start &
- sleep 3
script:
- npm run lint
- npm run test
- npm run build
- npm run test-e2e
after_success:
- test ${TRAVIS_TAG} && npm run package-all
deploy:
  provider: releases
  api_key:
    secure: YTmhVW4IDK0kzcyALecNGPAr135lrXJxRGCBN+pqiECE3xfdHQzcTfBpam8KRKugsKusuvp65ZuNelMB/P1nDPjIH6Y05H45JVWU5ypqALlilJN4QRGXFV0BZ1j0k8R8N803WUwrCJaWnorSfoNRs5FQ77AlfpSBcTqllHoja3lrROLnH7c14iSIC9Tkcd105HNf82xm4OxmVCGE6QffXv/o+ytAmZLwYL7x7+SrHkddgLNtJTgIF80PH6YaskuKu3GYnKdHn6/LO8yCw33qo7YfTaoIUFQNB6R2ryEXCdbD4VNvr5O7FCLyHKqcNKeoZ6LuGyBKVo/VDKFSo3AXBMJjaF+JMTGX3RFcpiZa18VHCAH5RR76EnEnfo49xKW2yWBBDz22eVFNd3nLRnUVbZ1FInPsn/s0i2AaFDWAYftxCRhIfJe/lKrO4JInZBW5Mx3P93tQwFt9y5UMHa1lV7SvMy7GI3ZFHcRY99oD+FUPxffnQowznCwo3IjhBVq811Vob+UVu2EURCIa6E1+oOMWeIPdr/Liu1IVN//itMsF9suJGjDlx/+4n+G/0Vx3tLDj/0GzzGkqOjmKi0DnVuXo1ekzRd7CBvnF7ooOQx2XxkFuKHXkjNyPHqShf6wV8+XvFcmej3vYL4K5gxJf3PlP2U5M7/HeEWW9Th/KEcg=
  file:
	-	release/darwin-x64
	- release/win32-x64
  on:
    repo: uraway/todo-electron
		tags: true
